[project]
name = "s3-scripts"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "anytree>=2.13.0",
    "cloudpathlib>=0.21.1",
    "jinja2>=3.1.6",
    "typed-argument-parser>=1.10.1",
]
